version: '3'

services:
  proxy:
    image: traefik:2.0
    command: 
      --api.dashboard=true  
      --providers.docker
      --providers.docker.swarmMode=true
      --providers.docker.network=proxy
      --providers.docker.exposedByDefault=false
      --global.sendAnonymousUsage=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - "traefik.http.services.api.loadbalancer.server.port=8080"
        - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
        - "traefik.http.routers.api.service=api@internal"
    networks: 
      - proxy
    ports:
      - 80:80
      
  site1:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html/
    deploy:
      labels:
        - traefik.enable=true
        - "traefik.http.routers.site1.rule=Host(`web.localhost.org`)"
        - traefik.http.services.site1.loadbalancer.server.port=80
    networks: 
      - proxy


networks:
  proxy:
    external:
      name: proxy
